# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cmZqPMJSkAO3VlPItN5L-AgUNfPe1o22
"""

# -*- coding: utf-8 -*-
"""Untitled18.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1ANoV7AhqUPwgpLl_aIF-6euL39uLdxmy
"""

import numpy as np

def unit_vector(v):
    return v / np.linalg.norm(v)
u = np.array([1, 1, -2])
print(unit_vector(u))